# v2 syntax
version: "2"

volumes:
  mysqldata:
   
services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: accordous-mysql
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysqldata:/var/lib/mysql:delegated
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=accordous
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  backend:
    build: ./backend
    container_name: accordous-backend
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend:delegated
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: accordous-frontend
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend:delegated
    depends_on:
      - backend
    
  nginx:
    image: nginx:1.17-alpine
    container_name: accordous-nginx
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/backend:ro,delegated
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
